<a href="https://colab.research.google.com/github/mixhub10/dl16/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ch02_numpy.ipynb
- numpy 공부

In [ ]:
# chap02 - numpy
import numpy as np


In [ ]:
# ndarray
a = np.array([1, 2, 3])

print(a[0])
a, type(a)

1


(array([1, 2, 3]), numpy.ndarray)

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(b)

b[0][2]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


3

In [ ]:
a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

a.shape,a.ndim,a.dtype,a.itemsize,a.size


((3, 3), 2, dtype('int64'), 8, 9)

In [ ]:
np.zeros( (3, 4) )	


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3, 4), dtype=np.int32 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:

x = np.ones(5, dtype=np.int64)

x


array([1, 1, 1, 1, 1])

In [ ]:

print(np.arange(5))

print(np.arange(1, 6))

np.arange(1, 10, 2)


[0 1 2 3 4]
[1 2 3 4 5]


array([1, 3, 5, 7, 9])

In [ ]:

np.linspace(0, 10, 101)


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [ ]:

# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:

# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])
x,y

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [ ]:
# np.concatenate((x, y), axis=0)
# np.concatenate((x, y), axis=1)

# np.vstack((x, y))
np.hstack((x, y))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# reshape
a = np.arange(12)

a.shape


(12,)

In [ ]:
# a.reshape(3, 4)

# a.reshape(6, -1)
a.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:

array = np.arange(30).reshape(-1, 10)

array, array.shape


(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), (3, 10))

In [ ]:

arr1, arr2 = np.split(array, [3], axis=1)

arr1,arr2


(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]]), array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19],
        [23, 24, 25, 26, 27, 28, 29]]))

In [ ]:
# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [ ]:
a1 = a[np.newaxis, :]

a1, a1.shape


(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [ ]:
a2 = a[:, np.newaxis]

a2.shape


(6, 1)

### numpy - indexing & slicing

In [ ]:
# indexing & slicing
ages = np.array([18, 19, 25, 30, 28])

ages[1:3] , ages[:2] 


(array([19, 25]), array([18, 19]))

In [ ]:
y = ages > 20

print(y)
# 조건을 만족하는 데이터 선택
ages[ ages > 20 ]


[False False  True  True  True]


array([25, 30, 28])

In [ ]:
# 인덱싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 2])

a[0, 0] = 12

a


3


array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# 슬라이싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3]


array([[2, 3],
       [5, 6]])

### numpy 연산
- elementwise operation
- vectorwise operation

In [ ]:
# operation of arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[1, 1], [1, 1], [1, 1]])

result = arr1 + arr2

result


array([[2, 3],
       [4, 5],
       [6, 7]])

### 브로드케스팅 (broadcasting)

In [ ]:
miles = np.array([1, 2, 3])

result = miles * 1.6

result


array([1.6, 3.2, 4.8])

In [ ]:
# elementwise multiplication
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 * arr2

result


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
# vectorwise multiplication
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 @ arr2

result


array([[12, 12],
       [30, 30],
       [48, 48]])

In [ ]:
arr1.dot(arr2)

array([[12, 12],
       [30, 30],
       [48, 48]])

In [ ]:

A = np.array([0, 1, 2, 3])

10 * np.sin(A)


array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a.sum(),a.min(),a.max()


(45, 1, 9)

### argmax, argmin with axis

In [ ]:
a.argmin(),a.argmax()

(0, 8)

In [ ]:
a.argmin(axis=0),a.argmin(axis=1)

(array([0, 0, 0]), array([0, 0, 0]))

In [ ]:
a.argmax(axis=0),a.argmax(axis=1)


In [ ]:
a2 = np.array([[3, 2, 1], [4, 5, 6], [9, 7, 8]])
# a2.argmax(axis=0),a2.argmax(axis=1)

### Using Bing AI
> Question: Can you show me the python code that return index of maximum value in 2 dimensional numpy array?
---
> Answer  

```
import numpy as np

# create a 2D numpy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# get the index of the maximum value in the array
max_index = np.unravel_index(np.argmax(arr, axis=None), arr.shape)

print(max_index)
```
> This code creates a 2D numpy array and then uses the np.argmax() function to get the index of the maximum value in the array. The np.unravel_index() function is then used to convert the flattened index to a tuple of indices that can be used to index the array.

In [ ]:
import numpy as np

# create a 2D numpy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# get the index of the maximum value in the array
max_index = np.unravel_index(np.argmax(arr, axis=None), arr.shape)

print(max_index)

(2, 2)


In [ ]:
np.unravel_index(np.argmax(a2, axis=None), arr.shape)

(2, 0)

### Using Bing AI
> 질의: 3차원 넘파이 배열의 최소값의 인덱스를 확인하는 코드를 만들어줘.  
> 답변: 3D numpy 배열에서 최소값의 인덱스를 확인하는 파이썬 코드는 다음과 같습니다.

```
import numpy as np

# 3D numpy 배열 생성
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# 배열에서 최소값의 인덱스 가져오기
min_index = np.unravel_index(np.argmin(arr, axis=None), arr.shape)

print(max_index)
```
> 이 코드는 3D numpy 배열을 생성하고 np.argmin() 함수를 사용하여 배열에서 최소값의 인덱스를 가져옵니다. 그런 다음 np.unravel_index() 함수를 사용하여 평탄화된 인덱스를 인덱싱에 사용할 수 있는 인덱스 튜플로 변환합니다.

In [ ]:
import numpy as np

# 3D numpy 배열 생성
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# 배열에서 최소값의 인덱스 가져오기
min_index = np.unravel_index(np.argmin(arr, axis=None), arr.shape)

arr.shape, min_index

((2, 2, 3), (0, 0, 0))

In [ ]:
scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])    

scores.mean()
scores.mean(axis=1)
scores.mean(axis=0)

array([92.  , 80.5 , 78.75])

## 무작위수 배열

In [ ]:
# random numbers
np.random.seed(100)

# np.random.rand(5),np.random.rand(5)

# np.random.rand(5, 3)

# np.random.randn(5)

np.random.randn(5, 4)


array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

### [DIY] 
- 컬러 이미지 100장을 무작위로 생성
- 이미지 크기는 28 X 28

In [ ]:
image100 = np.random.randn(100, 28, 28, 3)
image100.shape

(100, 28, 28, 3)

In [ ]:
m, sigma = 10, 2

m + sigma*np.random.randn(5)


array([ 8.12600727, 10.07239857,  8.639449  ,  8.44707082,  9.82908791])

In [ ]:

mu, sigma = 10, 2 	# 평균과 표준 편차

np.random.normal(mu, sigma, 5)


array([10.09750826, 10.64421076,  8.47769239, 10.09356629,  9.31069176])

### np.unique()

In [ ]:
# unique()
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
# a.size
unique_values = np.unique(a)
unique_values



array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
uv, ui = np.unique(a, return_index=True)
uv,ui

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [ ]:
uv, uc = np.unique(a, return_counts=True)
uv,uc

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [ ]:
# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


x.flatten()



## pandas. matplotlib

In [ ]:
########################
# Pandas
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

########################
# matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()


import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()


X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()


import matplotlib.pyplot as plt 
import numpy as np 
  
X = np.linspace(-10, 10, 101) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 


import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 101) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 
