<a href="https://colab.research.google.com/github/mixhub10/dl16/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ch02_numpy.ipynb
##dl16
- numpy 복습

In [3]:
# chap02 - numpy
import numpy as np

# ndarray
a = np.array([1, 2, 3])

a

a[0]


1

In [4]:

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b

b[0][2]


3

In [5]:

a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

print(a.shape)

print(a.ndim)

print(a.dtype)

print(a.itemsize)

print(a.size)


(3, 3)
2
int64
8
9


In [6]:


print(np.zeros( (3, 4) )	)

print(np.ones( (3, 4), dtype=np.int32 ))

print(np.eye(3))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:


x = np.ones(5, dtype=np.int64)

x


array([1, 1, 1, 1, 1])

In [8]:

print(np.arange(5))

print(np.arange(1, 6))

print(np.arange(1, 10, 2))

print(np.linspace(0, 10, 101))


[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5 7 9]
[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [9]:

# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:

# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])

print(np.concatenate((x, y), axis=1))

print(np.vstack((x, y)))

print(np.hstack((x, y)))


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [11]:

# reshape
a = np.arange(12)

print(a.shape)

print(a.reshape(3, 4))

print(a.reshape(6, -1))


(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [12]:

array = np.arange(30).reshape(-1, 10)

print(array )

arr1, arr2 = np.split(array, [3], axis=1)

print(arr1)

print(arr2)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]]


In [13]:

# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

print(a.shape)

a1 = a[np.newaxis, :]

print(a1)

print(a1.shape)

a2 = a[:, np.newaxis]

print(a2.shape)


(6,)
[[1 2 3 4 5 6]]
(1, 6)
(6, 1)


In [14]:

# indexing & slicing
ages = np.array([18, 19, 25, 30, 28])

print(ages[1:3] )

print(ages[:2] )

y = ages > 20

print(y)

print(ages[ ages > 20 ])


[19 25]
[18 19]
[False False  True  True  True]
[25 30 28]


In [15]:

# 인덱싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 2])

a[0, 0] = 12

print(a)


3
[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [16]:

# 슬라이싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3]


array([[2, 3],
       [5, 6]])

In [17]:

# operation of arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[1, 1], [1, 1], [1, 1]])

result = arr1 + arr2

result


array([[2, 3],
       [4, 5],
       [6, 7]])

In [18]:

miles = np.array([1, 2, 3])

result = miles * 1.6

result


array([1.6, 3.2, 4.8])

In [19]:

arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 * arr2

result


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [20]:

arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 @ arr2

result


array([[12, 12],
       [30, 30],
       [48, 48]])

In [21]:

A = np.array([0, 1, 2, 3])

10 * np.sin(A)


array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [22]:

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a.sum())

print(a.min())

print(a.max())


45
1
9


In [23]:

scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])    

scores.mean(axis=0)


array([92.  , 80.5 , 78.75])

In [24]:

# random numbers
print(np.random.seed(100))

print(np.random.rand(5))

print(np.random.rand(5, 3))

print(np.random.randn(5))

print(np.random.randn(5, 4))


None
[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
[[0.12156912 0.67074908 0.82585276]
 [0.13670659 0.57509333 0.89132195]
 [0.20920212 0.18532822 0.10837689]
 [0.21969749 0.97862378 0.81168315]
 [0.17194101 0.81622475 0.27407375]]
[ 0.67272081 -0.10441114 -0.53128038  1.02973269 -0.43813562]
[[-1.11831825  1.61898166  1.54160517 -0.25187914]
 [-0.84243574  0.18451869  0.9370822   0.73100034]
 [ 1.36155613 -0.32623806  0.05567601  0.22239961]
 [-1.443217   -0.75635231  0.81645401  0.75044476]
 [-0.45594693  1.18962227 -1.69061683 -1.35639905]]


In [25]:

m, sigma = 10, 2

print(m + sigma*np.random.randn(5))

mu, sigma = 0, 0.1 	# 평균과 표준 편차

print(np.random.normal(mu, sigma, 5))


[ 7.53513097  8.91112168  8.66365653 10.01462913  8.77412253]
[ 0.12997481 -0.17330956 -0.09833101  0.03575078 -0.16135785]


In [26]:

# unique()
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)

unique_values


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:

# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


x.flatten()





[[1 3 5]
 [2 4 6]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])